name: Compile kernel

on:
  repository_dispatch:
    types:
      - Compile-kernel
  workflow_dispatch:

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          swap-size-mb: 1024
          temp-reserve-mb: 512
          root-reserve-mb: 1280
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E systemctl daemon-reload
          # sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> $GITHUB_OUTPUT
          df -h

      - name: Compile the kernel
        run: |
          cp -f kernel/config/config-6.1 compile-kernel/tools/config/config-6.1
          sudo ./recompile -k ${{ github.event.client_payload.kernel_version }} -a ${{ github.event.client_payload.kernel_auto }} -n -ffuqiangg -t gcc
          cd compile-kernel/output
          tags="$(ls *.tar.gz | sed 's/.tar.gz//')"
          echo "OUTPUT_TAGS=${tags}" >> $GITHUB_ENV
          echo "OUTPUT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        with:
          tag: kernel_${{ env.OUTPUT_TAGS }}
          artifacts: ${{ env.OUTPUT_PATH }}/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Telegram notification
        run: |
          MSG="✅ 内核编译完成 *${{ env.OUTPUT_TAGS }}*"
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown"
